platform :ios, '10.1'

target 'WakeUppApp' do
  
  use_frameworks!
  
  pod 'IQKeyboardManagerSwift'
  pod 'SDWebImage', '~> 4.0'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'IQDropDownTextField'
  pod 'CameraManager', '~> 4.0'
  pod 'TransitionButton'
  pod 'SwiftMessages'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  pod 'IGRPhotoTweaks'
  pod 'MediaBrowser'
  pod 'SwiftLinkPreview', '~> 2.3.0'
  
  pod 'OpalImagePicker'
  
  pod 'TwilioVideo' , '~> 2.2.0'
  pod 'TwilioVoice', '~> 2.0.0'

# User Zip amd unzip file and dir. | https://github.com/marmelroy/Zip.git
pod 'Zip'

# Export and Import Coredata | https://github.com/3lvis/Sync.git # V.: 4.1.3
pod 'Sync'

# Manage fabric crashlytics
pod 'Fabric'
pod 'Crashlytics'
end
