platform :ios, '10.0'
def required_pods
    pod 'Alamofire', '~> 4.5'
    pod 'IQKeyboardManagerSwift'
    pod 'Eureka'
    pod 'MBProgressHUD', '~> 1.1.0'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'SDWebImage', '~> 4.0'
    pod 'BSImagePicker', '~> 2.4'
    pod 'Firebase/Core'
    pod 'Fabric', '~> 1.7.2'
    pod 'Crashlytics', '~> 3.10.0'
    pod 'SnapKit', '~> 4.0.0'
    pod 'DZNEmptyDataSet'
    pod 'GoogleAnalytics'
end
target 'remone' do
    use_frameworks!
    inhibit_all_warnings!
    required_pods
    # Pods for remone
    target 'remoneTests' do
        inherit! :search_paths
        # Pods for testing
    end
end
target 'remoneLive' do
    use_frameworks!
    inhibit_all_warnings!
    required_pods
    # Pods for testing
end

